[General]
bypass-system = true
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, localhost, *.local
bypass-tun = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.168.0.0/16, 224.0.0.0/4, 255.255.255.255/32
dns-server = 8.8.8.8, 8.8.4.4, 1.1.1.1

[Rule]
# Russian domains on non-.ru TLDs -> DIRECT
RULE-SET,https://raw.githubusercontent.com/WhisperOfTheSteppe/ru-rules-dat/release/ru-domains-shadowrocket.list,DIRECT

# Russian TLDs -> DIRECT
DOMAIN-SUFFIX,ru,DIRECT
DOMAIN-SUFFIX,su,DIRECT
DOMAIN-SUFFIX,xn--p1ai,DIRECT

# Russian IPs -> DIRECT
RULE-SET,https://raw.githubusercontent.com/WhisperOfTheSteppe/ru-rules-dat/release/ru-ip-shadowrocket.list,DIRECT

# Private subnets -> DIRECT
RULE-SET,https://raw.githubusercontent.com/WhisperOfTheSteppe/ru-rules-dat/release/private-ip-shadowrocket.list,DIRECT

# Everything else -> PROXY
FINAL,PROXY
